services:
  - type: web
    name: simple-stock-crawler
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    healthCheckPath: /healthz
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
